# Generated by Django 4.2.30 on 2026-07-22 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0002_alter_produit_id'),
        ('boutique', '0002_produit_image'),
    ]

    operations = [
    ]
